---
- name: Ensure temp download directory exist
  file: state=directory path={{vagrant_tmp_dir}}
  tags: [ "packages","vagrant" ]
- include_tasks: Debian.yml
  when: ansible_os_family == 'Debian'
  tags: [ "packages","vagrant" ]
- include_tasks: RedHat.yml
  when: ansible_os_family == 'RedHat'
  tags: [ "packages","vagrant" ]
